# Generated by Django 4.1.6 on 2023-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
