# Generated by Django 4.1.6 on 2023-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_forumuser_first_name_alter_forumuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
