# Generated by Django 4.1.6 on 2023-02-14 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_forumuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Post'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='last_edit_day',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted_day',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_edit_day',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
