# Generated by Django 4.1.6 on 2023-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_entry_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
